# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    name: Test Reporter
  # You may pin to the exact commit or the version.
  # uses: dorny/test-reporter@6969ae6af5efb4ddb55b1e5aa1e1198de99e191c
  uses: dorny/test-reporter@v1.4.3
  with:
    # Name or regex of artifact containing test results
    artifact: # optional
    # Name of the check run
    name: 
    # Coma separated list of paths to test results
Supports wildcards via [fast-glob](https://github.com/mrmlnc/fast-glob)

  path: 
  - mocha-json

    reporter: 
    # Limits which test suites are listed. Supported options:
  - all
  - only-failed

    list-suites: # default is all
    # Limits which test cases are listed. Supported options:
  - all
  - only-failed
  - none

    list-tests: # default is all
    # Limits number of created annotations with error message and stack trace captured during test execution.
Must be less or equal to 50.

    max-annotations: # default is 10
    # Set this action as failed if test report contain any failed test
    fail-on-error: # default is true
    # Relative path under $GITHUB_WORKSPACE where the repository was checked out
    working-directory: # optional
    # GitHub Access Token
    token: # optional, default is ${{ github.token }}
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm test
